language: node_js
node_js:
- '8'
- '6'
script:
- yarn run lint
- yarn run build
#- yarn run start &
#- yarn global add nightwatch
#- yarn run sauce
#- pkill node
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sauce_connect:
    username: timelapse-sauce
  jwt:
    secure: Y4Ln74LgkdB739lVzn/pKFS25I5oYTapYOjrczWUgt3MYErE/dFtCoooXR5NCWVjsbKjLdtI2hlD6zhL98fDuLjE9aeRvQ0Z1HceAvtEHAX9qkfTi+dOY11PUS7Q91rg0n/cHWd4K+8/k0b+w9HlqHzbNqO32LIgrzDAnQqtopMVceiRoTlTI8qqSKMWg9l6sYe2LMwdq4OucL6P2DT9tsGLyCWU0qbLmOzTIYqKUrFX/9DEbPF6Pu5A/jeYt4OuKmLdcdtNWh3OoALjNon4tPEMg91qq9ted20T1YNoS64gT8xH/crQZ8LiQ7hI3xVBMNAMGneJp0CAnJfnRGjepndF183xmUyrSNiEc/u2+Fh2rKRWSRk+wdjeIEYsfekOtkoeOdaCFtlUV3igm4rG0VUu5RVHL6HlaCRox2iZ8exWqMY6mLFO8ccaMBKz9lL0pvb0NLQQH+Dx4+0QJL1WOF1mJbrG0N2kIgvDtSF6Et2n7cwaJcUqthe/lkcDqBEWuf2a3rZHCM4VwD7wvkt2RVKfWVIHBNJOuUxgsd5wHmBA7ExQcq/L3Ut+7VxFEkeR3LdjJ+6Kad8cC7b8PfMtsU1BUgJQKf5M24FBvbycCB4puJyfAMwVPTVxxK8xqIBzaCTxGLYI0qx1wjYm5cEHwDShUj/cYQfA4HxcrFmFBHA=
after_success:
   - chmod +x ./deploy.sh
   - ./deploy.sh
branches:
  only:
  - master
notifications:
  slack:
    secure: b7rIINdgPIaEQJ6HUkkIHNyUpeQuUQWBVYp76uGyoxFtS8a1aaoujlpxbtUrMWNlYstYxqtCeHiCgZB1Y7FyZEJnsw9prAUoS5q34gPZNjMXOq98MLh+m9Jh+cgGaQZS6PDa3kAeihc1wOSQVzIH1kNQIXPErTZ2dQjMTl3n1Wu/gTwUjN123ICzNHMsSnBKZgipfo5taVZvOF2wvRCFlgziAkRYhukRghpd883eN15UnAwhoKSdEBxzr1S8mKo5Ekl8EgmZYnHU7zQUhrh1x2l6tm2mj0U8qsYcZLCp9qv/u+3sO5t1VL3NkAQnnrvzuEvf4fypSWd9y/+IIbje/6S4JnSTHrIkAiuFd5ltiEZyLk6i0tqT/3l/BDfs3+/L3jdhIJQMsE3Ns8++TrW4a8SaUjlKIxzml1UJiLGhUk8sx+rkQS+IM7hFcZ6QDFiESeN5L/s73LHrA0d3rTjRFSweHss+8pbcYDMI4hFV9Nubg4DXSQ8u/Ph92oTOZRCov9CQwTlH/T997lVKeYqXsq4pZcYIFnJXhkGaoWOeSyOnh3vo92t0T81HpxDdfoQLZPcjKDJkMq/GQ24o0Ely5UPFZSL6cFCm52mj01B1cSYZ3wK7ieQ7A/idufK3S2885BVgtKJPYzHBDQGi4GAE40zOCFwONsyU1vEt6B7dKiQ=
